swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Simple API'
  description: 'A simple API to list users'



schemes:
- localhost
host: 3000
basePath: '/api'

paths:
  //users:
    get:
      tags:
      - users
      summary: 'Gets some users'
      description: 'Returns a list of all users.'
      operationId: "getUsers"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
         